### ISSUE TITLE
[Bug]: Wrong API Endpoints

### ISSUE THREAD

**Issue by blidhpxc** [eclipse-aaspe/server#304]
### Describe the bug

The API sndpints do not match with the official Endpoint.
For example the endpoint "/submodels/{submodelIdentifier}/submodel-elements/$path".
Official specification: https://app.swaggerhub.com/apis/Plattform_i40/SubmodelRepositoryServiceSpecification/V3.0.1_SSP-001#/Submodel%20Repository%20API/GetAllSubmodelElements-Path_SubmodelRepo

### To reproduce

For example: call the API "/submodels/{submodelIdentifier}/submodel-elements/$path" without the query "Level".

### Expected Behaviour

The API should work, because the query "Level" is optional, but it doesn't work. It response with a message saying that Level is reqired.

**Comment by Freezor** [comment]
@aorzelskiGH Why don't we set the default value for that? in the code we always use 'deep' as default. So the documentation is misguiding here

**Comment by Freezor** [comment]
@blidhpxc with the next nightly build [v0.3.1.60-aasV3-alpha-latest](https://github.com/eclipse-aaspe/server/releases/tag/v0.3.1.60-aasV3-alpha-latest). This will be solved.
