### ISSUE TITLE
AASX Blazor Server not able to connect to Package Explorer

### ISSUE THREAD

**Issue by smolloy1** [eclipse-aaspe/server#321]
**What I did:**

- Deployed an AASX Blazor Server application to Azure for a university project.
- Used the adminshellio/aasx-server-blazor-for-demo:main docker image for deployment.
- Successfully connected to the server using the AASX Package Explorer via a REST endpoint.
- Performed actions like loading, editing, and deleting AASX files through the Package Explorer. These changes were reflected on the server.

**The Problem:**

- Today, when trying to demonstrate the application and connect to the server on the application explorer, I encountered a "400 Bad Request" error.
- Querying /server/listaas in the browser returns nothing, suggesting an API issue.
- 
**What I've Tried:**

- Confirmed the application was working on June 12th using the original docker image (main) since I have a recorded demo from this date.
- Switched to docker image version 0.3.1.60-aasv3-alpha-latest but the error persists.
- Tried both the latest (2024-06-10) and an older (v2024-05-08.alpha) version of the Package Explorer - no success.

**Possible Cause:**

Since I haven't made any changes to the code, I suspect an issue with the current adminshellio/aasx-server-blazor-for-demo:main docker image.
 I am on Windows 11 for context and my home PC uses windows 10 but this shouldn't affect the API.

Additional Information

![image](https://github.com/eclipse-aaspe/server/assets/59944029/6070ca38-d6f3-49f4-aab0-3b7221b36e15)
![Screenshot 2024-07-01 191656](https://github.com/eclipse-aaspe/server/assets/59944029/0adaafdf-71f9-4699-8a1b-1f67f8552a77)

Any help would be greatly appreciated as I have to present this in a couple weeks. Thanks!

**Comment by Freezor** [comment]
Hi @smolloy1 theres currently a bug with some parameters for the endpoints. A bugfix is will hopefully be provided this week. In the meantime you can check if adding a value for each parameter temporarily fixes this issue

**Comment by Freezor** [comment]
HI @smolloy1  there is a new version [v0.3.1.67-aasV3-alpha-latest](https://github.com/eclipse-aaspe/server/releases/tag/v0.3.1.67-aasV3-alpha-latest), which should solve this issue. Can you try this out and give us feedback?

**Comment by smolloy1** [comment]
Hi, I will try it out today and let you know how it goes. Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smolloy1** [comment]
@Freezor I tried using the new version and the updated main from DockerHub but I am now getting a 403 error. Running URL/packages gives the same error. The packages have not changed since I was last using it. See the full error message below.

{
  "Messages": [
    {
      "Code": "Forbidden",
      "CorrelationId": null,
      "MessageType": "Error",
      "Text": "Cannot proceed as decodedAasId is null",
      "Timestamp": "07/04/2024 14:58:52"
    }
  ]
}

**Comment by smolloy1** [comment]
Hi any update on this? I have tried with default files and the "/packages" API call isn't working. Interesting the /shells call works but I need the "/packages" to link to the application viewer.

**Comment by tunanorth** [comment]
Is there any update here?

**Comment by hadifar** [comment]
Same problem here! @Freezor did you have any idea how to fix the issue?

I tried different versions but still cannot connect AASX server to Package explorer :(

**Comment by hadifar** [comment]
@smolloy1 Did you find a solution? :(
